#%RAML 1.0 Trait

headers:
  Authorization:
    description: This header will contains JWT token for authorization.
    type: string
    required: true
    example: "jkgfdajkhgsdjgheriy8tye5876ty5rthrnvguer8ityugfvbdsnkfgary8rfsudjbm"