#%RAML 1.0 Trait

headers:
  X-lyt-channel:
    description: This header will contains channel value.
    type: string
    required: true
    enum:
      - Mobile
      - WebApp
    example: "Mobile"
  X-lyt-OriginLanguage:
    description: This Header will contains origin language.
    type: string
    required: true
    example: "en"
  X-lyt-OriginMarket:
    description: This Header will contains Business market.
    type: string
    required: true
    example: "IND"