#%RAML 1.0 Trait

headers:
  ClientId:
    description: This Header will contains Client Id.
    type: string
    required: true
    example: "edsgfhyjn"
  ClientSecret:
    description: This Header will contains Client Id.
    type: string
    required: true
    example: "esgsdthyghjn"