#%RAML 1.0 Trait

headers:
  X-lyt-transactionId:
    description: This header will contains transaction ID.
    type: string
    required: true
    minLength: 36
    maxLength: 36
    example: "12345678-ghfghdgf-7yrtgfyh-iugfhygrt"
