#%RAML 1.0 ResourceType

traits:
  business : /trait/business-traits.raml
  clientIdSecret : /trait/clientIdSecret-traits.raml
  transactionId : /trait/transactionId-trait.raml
  authorizationJWT : /trait/autharizationJWT-trait.raml

types:
  errorResponse : /DataType/error-response-dataType.raml


  
